crpg2/crpg

src/Module.Server/ModuleData/characters.xml
src/Module.Server/ModuleData/dtv_data.xml

- Reduced count of ranged units across most waves
- Replaced missing ranged units with melee
- Tweaked rewards

mod: reduce dtv ranged unit count

---

src/Module.Server/Modes/Dtv/CrpgDtvServer.cs

Checks whether the `TimerComponent` has finished after the game has started. Then awards players if the timer expires.
As the `MissionLobbyComponent` also conducts a similar check to end the match, the reward check is executed at the start of `OnMissionTick()`

mod: fix dtv timer expiry reward

---

src/Module.Server/Common/Models/CrpgAgentApplyDamageModel.cs

Reduced base punch damage and str based bonus, added glove armor based bonus
Kick uses str bonus, so kick = bare hand punch
_**Old System**_
**48str**
- Vs unarmored, 10 body damage, 12 head
- Vs medium, 7 damage body, 10 head
- Vs Heavy, 7 bodyy, 7 head
**15str**
- Vs unarmored, 6 body damage, 7 head
- Vs medium, 4 damage body, 6 head
- Vs Heavy, 4 body, 4 head
_**New System**_
**15str, 33gloves (no gloves)**
- Vs unarmored, 8(5) body damage, 12(6) head
- Vs medium, 6(3) damage body, 8(4) head
- Vs Heavy, 6(3) body, 8(4) head
**48str, 33gloves (no gloves)**
- Vs unarmored, 10(6) body damage, 15(7) head
- Vs medium, 7(4) damage body, 10(6) head
- Vs Heavy, 7(4) body, 10(4) head
**30str, 33gloves (no gloves)**
- Vs unarmored, 9(5) body damage, 11(6) head
- Vs medium, 7(4) damage body, 9(5) …

mod: Apply glove armor to punch damage

---

src/Module.Client/GUI/CrpgMissionGauntletMainAgentCheerControllerView.cs

Increase bark limit to 5 for improved communication
The previous limit was found to be restrictive during tests conducted on the beta server, possibly harming communicating in-game, a limit of 5 offers enough ability to communicate without being too spammy.

mod: increase bark limit slightly to 5

---

data/constants.json

Increased infantryCoverageFactorForShieldCoef to 0.25 from 0.15 as per:

Increase infantry coverage factor for shield to 0.25

---

src/Module.Server/Modes/Dtv/CrpgDtvServer.cs

People were exploiting spawning in before wave 1 of a round would start. When you spawn in you would be eligible to get rewards, but when you go back to spec before wave 1 starts the bot count would not increase because bot count per player would only get increased if players were in the team on starting Wave 1.

mod: fix DTV bot count calculation

---

src/WebUI/src/pages/index.vue

Update homepage video YouTube URL
Have updated the homepage URL matching the current formatting (youtube-nocookie) to embed properly into the site, have tested the URL in question which does redirect to the right video.

webui: Update homepage video

---

src/Module.Client/GUI/Intermission/CrpgIntermissionVM.cs

Hides current map from the client during voting.
`MapPoolComponent.cs` casts a single vote `OnMissionEnd()`. This may impact the winning map if only one vote is cast by players.

mod: hide current map from voting screen

---

src/Module.Server/Common/Models/CrpgAgentStatCalculateModel.cs

Copied `AgentStatCalculateModel.SetAiRelatedProperties` from pre-v1.2.5 and replaced with a new method in `CrpgAgentStatCalculateModel.cs`, enabling the customization of AI stats.

mod: enable custom ai properties

---

src/Module.Client/GUI/Scoreboard/CrpgScoreboardSideVM.cs
src/Module.Client/GUI/TeamSelection/CrpgTeamSelectInstanceVM.cs

Adds attacker & defender icons to scoreboard and team selection pages

mod: enable conquest attacker/defender icons

---

src/Module.Server/Modes/Dtv/CrpgDtvServer.cs
src/Module.Server/Modes/Dtv/CrpgDtvSpawningBehavior.cs

Cleans up mounts at the end of a DTV round to prevent them getting stuck on flee-lines.
1. Round ends.
2. Kill all tagged mounts without a rider.
3. Remove tags from all remaining mounts (because they have a rider).
4. Tag all `MountsWithoutRiders`, and force them to panic.

mod: cleanup dtv horses

---

src/Module.Client/GUI/MapSpriteData.xml

Misplaced `</SpritePart>` tag causes client crash on startup caused by d849e1c

mod: fix map sprite data crash

---

src/Module.Client/GUI/Prefabs/MultiplayerScoreboardSideTop.xml
src/Module.Client/Module.Client.csproj

- Fixes typo in GauntletUI, preventing current Commanders being displayed on scoreboard.
- Removes unnecessary csproj object

mod: fix commander ui

---

src/Module.Client/GUI/Intermission/CrpgIntermissionVM.cs
src/Module.Client/GUI/Prefabs/CrpgIntermission.xml
src/Module.Server/ModuleData/Languages/CNs/std_native_strings_xml-zho-CN.xml
src/Module.Server/ModuleData/Languages/RU/std_native_strings_xml-rus.xml

Removes all map tiles from voting screen. `MapPoolComponent.cs` already casts 1 vote on the next map in rotation, so the winning map will be the one in rotation.

mod: remove map voting screen

---

src/Module.Server/ModuleData/dtv/dtv_characters.xml
src/Module.Server/ModuleData/dtv/dtv_data.xml

Pirate round was slightly overtuned. Lowered their stats and spawnrate to be more in line with the rest.

DTV: nerf Pirate round

---

src/Module.Server/Common/Models/CrpgAgentApplyDamageModel.cs

Increase ranged damage vs. dtv bots:
- Crossbow 2.5x
- Bow 1.5x
- Throwing weapons 2.0x

mod: increase ranged damage vs dtv bots

---

src/Module.Server/Common/ChatCommands/Admin/BanCommand.cs
src/Module.Server/Common/ChatCommands/Admin/KickCommand.cs

Change to make Ban & Kick non-verbose and stay between the Moderator and the user it was actioned against.
Currently ban and kick are both verbose commands in that they are announced to the server; this often goes against the grain in that it results in a peanut gallery of people going after the staff member who initiated the moderative action. This change serves to fix that.

Mod : Remove verbose messages from Admin commands

---

data/constants.json

Lower the shield coverage factor for infantry
This places the InfantryCoverageFactorForShieldCoef halfway between what it was before the buff and after, being done because 2-3 shield skill produces a noticeably larger forcefield than it should really have. This change will put it back into a normal space again.
Taken from: https://github.com/namidaka/itembalancing/pull/447 and moved to correct repo

mod: Lower Shield Forcefield

---

src/Module.Server/Modes/Conquest/CrpgConquestServer.cs

https://www.desmos.com/calculator/9dbcvybhez
capture speeds are too slow in lower population games. now scales between 0.5 - 0.1 from 12 - 160 players.

mod: scale conquest flag capture speed based on playercount

---

src/Module.Server/Common/Models/CrpgItemValueModel.cs

slightly reduces the extra damage polearms were afforded in 41278bf
also, `swingLengthTier` is now more sensitive to higher 2h polearm lengths - as these are by far the most powerful polearms within the class

mod: swing polearm length and damage budget reduction

---

src/Module.Server/Common/TeamSelect/CrpgTeamSelectServerComponent.cs

Auto assigns the player team if their first team was spectator. This allows players to play in rounds before a balance event (which never occurs in conquest after warmup).
Players who have been auto-assigned are then added to the `_playersWaitingForTeam` HashSet so they can be considered for balancing in Battle.

mod: fix conquest spectator bug

---

src/WebUI/locales/cn.yml
src/WebUI/locales/en.yml
src/WebUI/locales/ru.yml
src/WebUI/src/components/app/InstallationGuide.vue
src/WebUI/src/types/vite-components.d.ts

Fixing mistake applied to logon button that resulted in it being named 'Steam Workshop' as opposed to 'Steam'
Set en.yml/cn.yml/ru.yml platform back to 'Steam'
Changed Tab inside InstallationGuide.vue to static label

webUI: Fix Steam Logon button

---

data/constants.json

Increase handling @ lvl 5 & 6 Weapon Mastery
A slight increase to handling for Weapon Mastery at levels 5 & 6 to address feelings of slowness on weapons - Lvl 5 & 6 is the typical range of handling level most low levels will experience as this is what most common place builds end up with hence the importance for good feeling.

mod: low lvl handling buff

---

src/Module.Client/DataExport/ItemExporter.cs

@Meowkov reported issues with the exporter removing the 'value' field in weapons.xml when setting smokebomb price manually. This change removes that functionality, so crafters can set price overrides without it impacting the xml.

mod: keep value when generating stats for fixed price items

---

src/Module.Server/Common/Models/CrpgAgentApplyDamageModel.cs

Reduced polearm BvS damage by 25%.
Changed the final BvS value to be 4.0 for one- and two-handed axes (based on a new weapon class containing only those two), and 3.0 for everything else. Weapons that are not axes do not have a stun-user-on-hit-effect (aka cleave) which makes them less attractive to fight with. Previously this was off set by having axes be the premier BvS weapon over swords. With the introduction of more BvS polearms, axes were further pushed away from being an attractive weapon class, as the code previously only gave weapon class swords a lower BvS value. Now axes receive a higher BvS value, and everything else (including the polearms mentioned) receive the lower value.
This reduces the BvS damage of:
All polearms with BvS
The 5 one-handed maces with BvS
The 2 two-handed …

mod: polearm bvS Reduction

---

src/Module.Server/Common/CrpgSpawningBehaviorBase.cs
src/Module.Server/Common/Models/CrpgAgentStatCalculateModel.cs
src/Module.Server/Modes/TrainingGround/CrpgTrainingGroundSpawningBehavior.cs
src/Module.Server/ModuleData/crpg_captain_characters.xml
src/Module.Server/ModuleData/crpg_captain_class_divisions.xml

Agents were loading wrong stats from `CrpgAgentStatCalculateModel` in gamemodes where agents were not spawned during the same call of `SpawnAgents()`. This is because characters are now assigned a 'p' value, to identify different players when populating bot stats. However, in gamemodes where the spawning is more than once in a gamemode, the 'p' value of each agent would likely be set to 1.
`CrpgAgentStatCalculateModel` used this p value to set agent stats, causing the bug for these gamemodes.
I have refactored the code to use a separate set of character xml's for captain bots.

fix: agent desync

---

src/Module.Server/Rewards/CrpgRewardServer.cs

Calculates low population based on players who have a team, instead of including spectators.

mod: update lowpop logic

---

src/Application/Items/Commands/RefundItemCommand.cs
src/WebApi/Controllers/ItemsController.cs
test/Application.UTest/Items/RefundItemCommandTest.cs

adds a refund itemid api endpoint
with the implementation of #349 we can now create items that are disabled in the api by default (such as holiday items). we can now activate and deactive them without editing the items.json file, but if they are purchased or loomed, we need a way to refund them.

webapi: add refund command

---

src/WebApi/Workers/DonorSynchronizerWorker.cs

uses `StringSplitOptions.TrimEntries` to Trim white-space characters from each substring in the result. 
If [RemoveEmptyEntries](https://learn.microsoft.com/en-us/dotnet/api/system.stringsplitoptions?view=net-9.0#system-stringsplitoptions-removeemptyentries) and [TrimEntries](https://learn.microsoft.com/en-us/dotnet/api/system.stringsplitoptions?view=net-9.0#system-stringsplitoptions-trimentries) are specified together, then substrings that consist only of white-space characters are also removed from the result.
https://learn.microsoft.com/en-us/dotnet/api/system.stringsplitoptions?view=net-9.0

webapi: trim donor details

---

src/Module.Server/Common/Models/CrpgItemRequirementModel.cs

Goals:
Reduce 24 STR req xbows to 21
Reduce Templar Light Xbow to 15
Creates code area for easy tweaking of light and heavy in the future
Significant changes:
Final STR req is rounded up to the nearest 3, instead of down. This is why xbows have >20STR req despite that being the "maximum"
Checks for itemusage == crossbow.light to achieve the differentitation
Considerations
One of the horse loading xbows has dropped from 15STR to 12STR. I don't think that's a problem personally. Can always change the 1.85f increase in horseloading xbows to push this up more

Crossbow STR reqs adjustment

---

src/Module.Server/Common/CrpgRespawnTimerServer.cs
src/Module.Server/Modes/Conquest/CrpgConquestServer.cs
src/Module.Server/Modes/Siege/CrpgSiegeSpawningBehavior.cs

Added 0.5f spawn timer override for both teams on the start of a new stage in conquest
Respawn timer correctly displays remaining time if you change team
Respawn timer disappears if you spawn earlier than the timer

mod: improve respawn timer

---

src/Module.Server/CrpgSubModule.cs
src/Module.Server/MapRotation/ds_config_crpg_battle.txt
src/Module.Server/MapRotation/ds_config_crpg_battle_maps.txt

Randomize map rotation using the Fisher-Yates shuffle.
This change implements the Fisher-Yates shuffle algorithm to randomize the order of maps in the map rotation. Previously rotation was random on the initial map pick but after that followed the rotation downwards leading to a repetitive experience at times (as you eventually would always know what map comes next)
This change shuffles the map order each time the server is started, which works alongside processes already in place as the servers currently reboot nightly regardless, **_however is also a potential consideration to factor into this review as it could lead to (albeit minor) issues if we ever disposed of the nightly reboots._**

mod: Randomise map rotation

---

src/Module.Client/Module.Client.csproj
src/Module.Editor/Module.Editor.csproj
src/Module.Server/Common/KickInactiveBehavior.cs
src/Module.Server/Modes/Battle/CrpgBattleGameMode.cs
src/Module.Server/Modes/Conquest/CrpgConquestGameMode.cs
src/Module.Server/Modes/TeamDeathmatch/CrpgTeamDeathmatchGameMode.cs
src/Module.Server/ModuleData/multiplayer_strings.xml

- Users are now moved to spectator instead of kicked if possible
- Warning sound now plays when a player is warned about inactivity
- Inactivity timer reduced to 30 seconds from 60 in battle
- Inactivity timer only checks during the first 65 seconds of each round in battle
- Admins are no longer kicked due to inactivity

mod: rework inactivity handling

---

src/Module.Server/Common/Models/CrpgItemValueModel.cs

See https://github.com/namidaka/itembalancing/pull/528 for effects
1h maximum price increased to 9000 (+2000)
Shield maximum price decreased to 5000 (-2000)
Increased the cost of 1h mace swing stats
Decreased the cost of canknockdown
Increased the cost of length for 1h maces
Increased the cost of blunt for all weapon types
Increased the cost of BvS for two handed polearms and 1h maces
Intended effects:
Make powerful 1h more expensive to reflect their power level, whilst not increasing average cost for sword and board classes through shield price reduction, also encouragaing players to take shields more often in general. NOTE this does lower non-1h shield classes overall cost slightly, most notably hoplite/cavalry. If we don't like this can remove the price change altogether, or just …

Exporter blunt, BvS, 1h mace budget adjustment

---

src/Module.Server/Common/AiComponents/DtvAiComponent.cs
src/Module.Server/Helpers/MathHelper.cs
src/Module.Server/Modes/Dtv/CrpgDtvServer.cs
src/Module.Server/Modes/Dtv/CrpgDtvSpawningBehavior.cs

DTV bots now have a timer (between 24 - 36 seconds) until they will target the viscount. The timer is reset when they either attack or get attacked by a defender. 
When bots first spawn the timer is 60 seconds
This is to reduce the amount of cheese possible in dtv by abusing bots' targetting unreachable players.
Difficulty is likely to spike significant from this change, so further balancing of bots (count / stats) may be required following feedback

mod: dtv bot aggro timer

---

src/Launcher/Program.cs
src/Module.Client/DataExport/IDataExporter.cs
src/Module.Client/DataExport/ItemExporter.cs
src/Module.Client/DataExport/SettlementExporter.cs
src/Module.Client/Module.Client.csproj
src/Module.Client/Properties/launchSettings.json
src/Module.Server/Common/Models/CrpgAgentApplyDamageModel.cs
src/Module.Server/Common/Models/CrpgAgentStatCalculateModel.cs
src/Module.Server/Common/Models/CrpgItemRequirementModel.cs
src/Module.Server/Common/Models/CrpgItemValueModel.cs
src/Module.Server/Common/Models/CrpgStrikeMagnitudeModel.cs
src/Module.Server/CrpgSubModule.cs
src/Module.Server/SubModule.xml

Adds support for Musket & Pistol type & weapon classes
Adds support for Bullets type
Adds support for Cartridge weapon class
Removes Bannerlord.Harmony module, replaced with Lib.Harmony 2.2.2 so crafters do not need to rely on harmony installation.

mod: add firearm support for exporter & remove harmony module

---

src/Module.Server/HarmonyPatches/DecideWeaponCollisionReactionPatch.cs

Adds harmony postfix to set `MeleeCollisionReaction` for axes to `MeleeCollisionReaction.SlicedThrough` when hitting an agent.

mod: add axes slicedthrough meleecollisionreaction

---

src/Module.Server/HarmonyPatches/HandleClientQuitFromCustomGamePatch.cs

```Application: DedicatedCustomServer.Starter.exe
CoreCLR Version: 6.0.1222.56807
.NET Version: 6.0.12
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> System.InvalidOperationException: Sequence contains more than one matching element
at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
at TaleWorlds.MountAndBlade.DedicatedCustomServer.DedicatedCustomGameServerHandler.HandleClientQuitFromCustomGame(PlayerId playerId)
at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
--- End of inner exception stack trace ---
at …
```

fix: patch crash when more than one NetworkPeer found with VirtualPlayer.Id

---

src/Module.Server/Modes/Siege/CrpgSiegeSpawningBehavior.cs

Prevents attackers from spawning for first 20 seconds. If the respawn period for attackers is 12, they would actually spawn after 24 seconds.
closes #477

mod: add conquest attacker spawn delay

---

src/Module.Server/Common/CrpgSpawningBehaviorBase.cs

Removes the extra weapon slot from being checked for a valid melee or throwing weapon to spawn. 
closes #482

mod: remove extra slot from spawn weapon check

---

src/Module.Server/Common/AiComponents/DtvAiComponent.cs

DTV aggro timer scales linearly with population up to 32 players, effectively doubling once 32 players are reached.

mod: add dtv aggro timer population scale

---

data/constants.json
src/Module.Server/Modes/Battle/CrpgBattleServer.cs
src/Module.Server/Modes/Dtv/CrpgDtvServer.cs
src/Module.Server/ModuleData/dtv/dtv_data.xml
src/Module.Server/Rewards/CrpgRewardServer.cs

- Multiplier when losing in battle is now reduced by 2x instead of 5x
- Valour will now be awarded on teams with 2 or more players
- Increase upkeep by ~9%
- Reduced DTV Upkeep discount from 25% to 20%
- Reduced DTV rewards in higher rounds by around 5%

mod: modify economy and rewards

---

src/Module.Server/Common/Models/CrpgStrikeMagnitudeModel.cs

Buffed cartridge penetration to 0.8, to help diversify guns from crossbows. A 2 damage increase for shooting targets >40 armor, a 1 damage increase for shooting targets <30 armor. Highest damage xbow + highest damage bolts still most damaging (at least up to 100 armor).
The cons of the gun over the xbow (harder to aim, smoke giving away posistion, less abusable reload) the buff not being accounted for in budget seems fair.
I'm not convinced it's as weak as some of the feedback we've received makes out - certainly on the STR req front. Dropping to 18STR would too easily allow enough WPF to be very competent in melee and the gun, at which point I think it would objectively be too powerful.

Changed cartridge pen to 0.8

---

src/Module.Client/GUI/HudExtension/CrpgHudExtensionHandler.cs
src/Module.Client/GUI/HudExtension/CrpgHudExtensionVm.cs
src/Module.Client/GUI/Warmup/WarmupHudUiHandler.cs
src/Module.Client/GUI/Warmup/WarmupHudVm.cs
src/Module.Server/Modes/Battle/CrpgBattleServer.cs
src/Module.Server/Modes/Conquest/CrpgConquestServer.cs
src/Module.Server/Modes/Dtv/CrpgDtvServer.cs
src/Module.Server/Modes/Siege/CrpgSiegeServer.cs
src/Module.Server/Modes/TeamDeathmatch/CrpgTeamDeathmatchServer.cs
src/Module.Server/Modes/Warmup/CrpgWarmupComponent.cs
src/Module.Server/Modes/Warmup/CrpgWarmupSpawnFrameBehavior.cs
src/Module.Server/ModuleData/Languages/CNs/std_module_strings_xml-zho-CN.xml
src/Module.Server/ModuleData/Languages/RU/std_module_strings_xml-rus.xml
src/Module.Server/Rewards/CrpgRewardServer.cs

Overhauls the warmup behaviour
- Warmup gives a constant 2x multiplier (1x if solo) reward every 30 seconds.
- Warmup will only end after timer (to change map) or if gamemode specific requirements are met (after 30 seconds).
- Battle (10) & Conquest (14) have minimum playercount requirements
- Other modes will just need 1 player to skip warmup
- Added players required to start indicator to UI
- Fixed some originally missing notifications / timer updates for clients

mod: warmup overhaul

---

src/WebUI/src/services/item-service.ts

Increase ItemIsNewDays to 14 
Increases the duration Items are considered 'New' on the site to 14 days.
This ensures a wider period in which items are considered New enabling faster and easier testing/noticing of the fresh items we add into the mod.

webUI: Increase duration items are new

---

src/Module.Server/Modes/Warmup/CrpgWarmupComponent.cs

fixes #523 - will probably need to monitor as the first reward tick is only 30 seconds which may not be enough time for players to reach the threshold.

mod: add warmup reward check if not enough players to start

---

src/Module.Server/ModuleData/managed_core_parameters.xml

Lower DamageInterruptAttackThreshold for cut from 9 to 7
Glance threshold currently sets the minimum range for a stun to occur as being 9 damage, often cut (more likely to deal less damage to people in armour) hits below this threshold resulting in no stun occurring. This is frustrating for combat. Blunt and Pierce tend to do more damage than this or will do more damage even on a swing that should be a glance, hence why only Cut threshold is being lowered.
This change is being made for the purpose of improving performance of cut weapons without a direct buff to their damage.

Lower DamageInterruptAttackThreshold for cut from 9 to 7

---

src/Module.Client/GUI/CrpgMissionMarkerVM.cs

Added a check that the agent is still alive.
System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'
The error occurs when trying to access the agents visuals. Doing a null check on AgentVisuals does not solve the issue.
Its kind of an ugly looking change in the diff. I just added an extra check.

mod: When VIP is already dead, highlighting causes a client crash.

---

src/Module.Server/Common/Models/CrpgAgentApplyDamageModel.cs

Enforce pierce-only damage type for mount rearing mechanics.
Mounts can only be forced into a rear state if the blow's damage type is Pierce. 
This aligns with gameplay intent to reward proper weapon use (e.g., spears, lances) for dismount maneuvers, and avoids unintended rears from other damage types like blunt or cut.
This change preserves all existing TaleWorlds base logic by deferring to the original `DecideMountRearedByBlow()` implementation after verifying the damage type. The goal is to maintain compatibility with upstream changes while enforcing custom gameplay rules in Crpg.
See: MissionCombatMechanicsHelper.DecideMountRearedByBlow in current compiled TW logic for reference.
Also see: https://github.com/verdie-g/crpg/commit/273afcf4977e61309531ed4a05d440d12ff2e2c1 & …

mod: Re-enforce pierce-only damage type for mount rearing mechanics

---

src/Module.Server/Common/Models/CrpgAgentStatCalculateModel.cs
src/Module.Server/ModuleData/combat_parameters.xml

Remove slowdown applied to 1h thrust, fix collision parameters to line up with original animation.
Based on feedback provided by users (special thank you to Defodijabox) and further testing, it was discovered that a slowdown that did not need to be present was still in place for 1h, furthermore, this was also obscuring deeper issues with 1h thrust attacks. This change removes a now unnecessary ready speed penalty for 1h weapons and addresses separate issues affecting thrust performance.
See the following video for reference:
https://cdn.discordapp.com/attachments/1186742521255182356/1376356318889115698/BeforeAfter1HSTAB.mp4?ex=68350735&is=6833b5b5&hm=78f30dcc5fe66174b556602f99fa1a097734410307e846e6475006bbe2f5e03b&

mod: Fix remaining 1h stab issues and adjust thrust collision parameters

---

src/Module.Server/Common/Models/CrpgAgentStatCalculateModel.cs
src/WebUI/src/services/characters-service.ts

Increased the strength requirement to have no movement penalty when attacking, to match with pike changes where new maximum reach weapon is 400. The intention is to further limit agility build from combining very high movement speeds with very long weapons. As this only applies during attacks, won't affect general movement speed or eg, ranged taking a slightly longer melee weapon until they need to use it.
~~I am unsure if/how this would require updating to show on the website correct, or if Orle has performed magic and it's automatic.~~ Updated the WebUI section
Tested changes and works as intended

mod: Increased STR req for longer weapons

---

src/Module.Server/Common/Models/CrpgAgentStatCalculateModel.cs

Increased TopSpeedReachDuration by 0.5s, from 1.0 seconds to 1.5 seconds, for characters holding a ranged weapon.
Edit: Poor wording in my original title, I don not want to make ranged have a +50% time to top speed based off the existing formula, just increase their existing slowdown of 1s by 0.5s

mod: Time to reach maximum speed +50% when holding a ranged weapon

---

src/Module.Server/Common/Models/CrpgAgentApplyDamageModel.cs

Add 10% damage bonus for 1h swords under strict conditions.
This change applies a 10% melee damage bonus to attacks made with one-handed swords, but only under the following conditions:
- The attack is a swing (not a thrust)
- The damage type is cut
- The agent is not mounted
- The agent has no shield equipped (offhand or in inventory)
- The agent has no ranged weapons in their inventory
The logic is evaluated per attack, ensuring that the bonus dynamically reflects the agent's current state. This incentivizes a reason to play a 1h Sword without a shield.
This has been tested in-game to confirm all of the conditions work as expected.
Video for reference:
https://cdn.discordapp.com/attachments/1186742521255182356/1377032789249101856/1hSwashBucklerBuff2.mp4?ex=68377d38&is=68362bb8&hm=677208b …

mod: Add 10% damage bonus for 1h swords under strict conditions

---

src/Module.Server/Common/Models/CrpgAgentStatCalculateModel.cs

Reduced one handed polearm final thrust speed by 10%. Not achievable through crafting because of the crafting process, would tank handling.
One handed polearms, whether it be on foot as hoplite or mounted cavalry, are extremely fast to stab even with low WPFs. A reduction in their thrust speed will make them much more unusable at low WPFs and potentially alleviate some issues we are seeing with instant stabs.

One handed polearm global thrust speed reduction

---

src/Module.Server/Common/Models/CrpgAgentApplyDamageModel.cs

Increased the final BvS value to 5.0 (from 4.0) for axes and 3.5 (from 3.0) for non-axes to help offset the increase in power shielders will receive and provide a natural, stronger counter to them.

Increased BvS to 5.0 for axes and 3.5 for others

---

src/Module.Server/ModuleData/managed_core_parameters.xml

Increased maximum combat speed from 0.94 to 0.96. This value is in relation to the characters maximum movement speed, and is the speed that can be moved when blocking/attacking. Weapon length also plays an impact, this is the final modifier - short weapons are able to reach high combat speeds, so this will benefit short weapons/1h/shielders.

Increased maximum combat speed

---

src/Module.Server/ModuleData/combat_parameters.xml

Tweak `collision_check_ending_percent` from `1` to `0.52` to reduce the duration during which 1h weapon stabs can register a hit after the animation begins.
This change addresses a noted problem where stabs continued to hit for too long after the stab portion of animation finished, leading to problematic behaviour in combat. Based on local testing the adjusted value better aligns the hit window with the animations visual end. Testing indicates improved behaviour without introducing further issues. Deploying this change to production will allow validation in actual combat and may result in further tuning based on feedback.

mod: Fix overly long hit window on 1h weapon stabs

---

src/Module.Server/Common/Models/CrpgAgentApplyDamageModel.cs

Normalised the damage done to mounts across all melee weapons, whether mounted or not, and all ranged weapons when on foot. This:
- Increases the threat ranged can pose to cavalry, offset by mount armour
- Decreases the large spike in damage mounts might receive from infantry polearm pierce thrusts
- Incentivises cavalry to hunt other cavalry by making their damage more impactful
To go with cavalry refund: https://github.com/crpg2/itembalancing/pull/638

Removed cavalry breaker and normalised damage to mounts

---

src/Module.Server/ModuleData/native_parameters.xml

Increases the mount acceleration multiplier (used in native acceleration model) to give cavalry more fine-control, improving the "feel" when trying to engage aware infantry.

Increase mount acceleration

---

src/Application/Characters/Commands/UpdateCharacterCharacteristicsCommand.cs
src/Module.Server/Common/Models/CrpgAgentStatCalculateModel.cs
src/Module.Server/Common/Models/CrpgStrikeMagnitudeModel.cs
src/WebUI/locales/en.yml
src/WebUI/locales/ru.yml
src/WebUI/src/composables/character/use-character-characteristic.ts
test/Application.UTest/Characters/UpdateCharacterCharacteristicsCommandTest.cs

**Throwing**
- Decreased the impact of damage on throwing weapon accuracy (apart from stones)
- Increased the impact of WPF on wind up speed
- Increased the maximum penalty for movement
- Increased the maximum penalty for rotation
- Increased the minimum and decreased the maximum wind up speed
- Increased the minimum and decreased the maximum reload speed
- Decreased the combat speed multiplier
**Armour pen (increasing is worse)**
- Increased stones to 1.2f
- Decreased all other throwing weapons to 1.0f
**Skills**
- WIP Power throw is now every 6STR instead of 3STR, no change to % increase in damage
Needs https://github.com/crpg2/itembalancing/pull/641

Throwing overhaul

---

src/WebApi/Program.cs
src/WebUI/src/models/platform.ts
src/WebUI/src/services/platform-service.ts

Remove Xbox/Microsoft logon portion of logon button.
Following https://github.com/crpg2/crpg/pull/551 I noted that Xbox still had the logon method listed under our Logon button which would inevitably fail out in an error when used. This change removes some API/UI components that are keeping this in place.

webAPI/webUI: Remove Xbox logon

---

src/Module.Server/Common/Models/CrpgAgentApplyDamageModel.cs

Crush through change to reduce chances on "full" melee builds, whilst keeping viable against more AGI characters. New chances:

Crush through reduction
