- src/Module.Server/Common/Models/CrpgAgentApplyDamageModel.cs
Table Provided here : https://docs.google.com/spreadsheets/d/1A5ynImHS9oKFTJzyX9l2YUg8bHNyuh8T6uhfXxOBENA/edit?usp=sharing
> mod : Crusthrough rework

- src/Module.Server/Modes/Battle/CrpgBattleClient.cs
- src/Module.Server/Modes/Battle/CrpgBattleServer.cs
- src/Module.Server/Modes/Battle/CrpgBattleSpawnFlagMessage.cs
- src/Module.Server/Modes/Battle/FlagSystems/AbstractFlagSystem.cs
- src/Module.Server/Modes/Battle/FlagSystems/CrpgBattleFlagSystem.cs
- src/Module.Server/Modes/Skirmish/CrpgSkirmishFlagSystem.cs
Also seperated the skirmish flag system from battle flag system
> mod: change the battle flag system to warband style

- src/Module.Server/ModuleData/characters.xml
- src/Module.Server/ModuleData/class_divisions.xml
- src/Module.Server/ModuleData/dtv_data.xml
- Added new Khuzait faction
- Shuffled some waves to scale difficulty logically
- Added halloween items & final wave 
- Changed tincan horse armour
> mod: DTV additions

- src/Application/Common/Services/IPatchNotesService.cs
- src/WebUI/locales/cn.yml
- src/WebUI/locales/en.yml
- src/WebUI/locales/ru.yml
- src/WebUI/src/components/app/PatchNotes.vue
- src/WebUI/src/models/patch-note.ts
Now you don't have to enter the patch version in the title
> feat: patch notes add tagName

- src/Module.Server/ModuleData/characters.xml
- src/Module.Server/ModuleData/dtv_data.xml
**Defend the Viscount**
- Increase Tin can & dwarf unit counts
- Reduce Khuzait Horseman ammo count
- Reduce Khuzait faction unit count
- Amazonian loadout change
- Fancy Lads weapon changes
> mod: DTV bot tweaks

- src/Module.Server/Modes/Conquest/CrpgConquestServer.cs
Rewards players for the stage ending before final stage check
fixes #138
> mod: fix conquest reward

- src/Module.Server/Common/Models/CrpgAgentApplyDamageModel.cs
- src/Module.Server/Modes/Dtv/CrpgDtvServer.cs
Also removed redundant healing of Viscount if damaged by players
> mod: viscount cannot be damaged by players now

- src/Module.Server/Modes/Dtv/CrpgDtvGameMode.cs
- src/Module.Server/Rewards/CrpgRewardServer.cs
- added an option to toggle low population upkeep settings
- removed low population upkeep exemption from DTV
> mod: add low population upkeep toggle

- src/Module.Server/ModuleData/monsters.xml
Reduce bot weight to 0
Reduce tincan & dwarf bot weight to 10
> mod: reduce dtv bot weight further

- src/WebUI/src/components/item/ItemParam.vue
- src/WebUI/src/services/item-service.ts
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
> webui: item prop compare fix

- src/WebUI/src/components/shop/ShopGridItemBuyBtn.vue
- src/WebUI/src/pages/shop.vue
> webui: accent upkeep in shop table

- src/Module.Server/MapRotation/a_maps.txt
New rotation for battle mode, reduced to 30 maps. Also added 2 new battle maps: Vritannis and Frosthaven. PRs pending.
> New battle rotation (reduced to 30 maps)

- data/constants.json
- src/Application/Characters/Commands/RespecializeCharacterCommand.cs
- src/Application/Common/Constants.cs
- src/Application/System/Commands/SeedDataCommand.cs
- src/Module.Server/Common/CrpgConstants.cs
- src/WebUI/locales/cn.yml
- src/WebUI/locales/en.yml
- src/WebUI/locales/ru.yml
- src/WebUI/src/pages/characters/[id]/index.vue
- src/WebUI/src/services/characters-service.ts
- src/WebUI/src/utils/date.ts
- src/WebUI/tailwind.config.ts
- test/Application.UTest/Characters/RespecializeCharacterCommandTest.cs
> mod: free respec post window

- src/Module.Server/ModuleData/characters.xml
- src/Module.Server/ModuleData/class_divisions.xml
- src/Module.Server/ModuleData/dtv_data.xml
Added lieutenants to wave 1 and 2 for every round (weaker mini bosses)
Also added two new rounds - Templars and Varangians
Also changed the viscount his gear.
> mod: add DTV lieutenants, extra rounds, and viscount equipment

- data/constants.json
Update constants.json to halve reforge cost for the x-mas event
> update to halve reforge cost (xmasEvent)

- src/Module.Server/Modes/Dtv/CrpgDtvClient.cs
> mod: fix dtv viscount under attack message

- src/Module.Server/ModuleData/dtv/dtv_characters.xml
Added heirloomed versions for the boss their weapons (and mounts). 
Changed The Viscounts weapon back to 1h, hopefully he will block a bit more and not die to a single farmer.
Changed a few names so they fit better with their round
> DTV Bosses have heirloomed weapons

- src/WebUI/src/components/app/MainNavigation.vue
- src/WebUI/src/components/app/PatchNotes.vue
- src/WebUI/src/layouts/default.vue
- src/WebUI/src/pages/index.vue
We don't have to write it in the patch note.
> webui: patch version to header

- src/Module.Server/Common/Models/CrpgAgentApplyDamageModel.cs
- src/Module.Server/Modes/Dtv/CrpgDtvClient.cs
- src/Module.Server/Modes/Dtv/CrpgDtvGameEnd.cs
- src/Module.Server/Modes/Dtv/CrpgDtvServer.cs
- src/Module.Server/Modes/Dtv/CrpgDtvSpawningBehavior.cs
- src/Module.Server/Modes/Dtv/CrpgDtvVipUnderAttackMessage.cs
- src/Module.Server/Modes/Dtv/CrpgDtvViscountUnderAttackMessage.cs
- src/Module.Server/ModuleData/dtv/dtv_characters.xml
- src/Module.Server/ModuleData/dtv/dtv_class_divisions.xml
Added the Viscountess to spawn in DTV.
> DTV Viscountess

- src/Module.Server/ModuleData/dtv/dtv_characters.xml
The templar had bandit body armor, changed it to something more suitable.
FOR DTV
> Changed templar body armor

- src/Module.Server/ModuleData/multiplayer_strings.xml
> mod: fix conquest typo

- data/constants.json
revert respecializePriceHalfLife -> 24
revert itemReforgeCostPerRank -> 0.0 ,40000.0, 90000.0, 150000.0
> update constants.json to revert xmas bonuses

- src/Module.Client/GUI/MapSpriteData.xml
- src/Module.Server/MapRotation/e_maps.txt
- src/Module.Server/ModuleData/Languages/CNs/std_native_strings_xml-zho-CN.xml
- src/Module.Server/ModuleData/Languages/RU/std_native_strings_xml-rus.xml
- src/Module.Server/ModuleData/multiplayer_strings.xml
> Add DTV map Musa Point

- src/Application/Characters/Queries/GetLeaderboardQuery.cs
- src/WebApi/Program.cs
- test/Application.UTest/Characters/GetLeaderboardQueryTest.cs
**Patch notes:**
- Distinct by user in Leaderboard.  @or2e 
- Now the leaderboard shows 1 of the best user characters.
- In the future, maybe we'll do character grouping (will be collapsed in the leaderboard).
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
> feat: Leaderboard tweak

- src/Application/Restrictions/Models/RestrictionViewModel.cs
- src/Application/Users/Commands/UpdateUserNoteCommand.cs
- src/Application/Users/Models/UserPrivateViewModel.cs
- src/Application/Users/Models/UserPublicViewModel.cs
- src/Application/Users/Queries/GetUserByIdQuery.cs
- src/Application/Users/Queries/GetUserByPlatformIdQuery.cs
- src/Application/Users/Queries/GetUsersByIdQuery.cs
- src/Application/Users/Queries/GetUsersByNameQuery.cs
- src/Domain/Entities/Users/User.cs
- src/Persistence/Migrations/20240103044248_AddUserNoteField.Designer.cs
- src/Persistence/Migrations/20240103044248_AddUserNoteField.cs
- src/WebApi/Controllers/UsersController.cs
- src/WebUI/src/components/character/CharacterMedia.vue
- src/WebUI/src/components/user/UserClan.vue
- src/WebUI/src/components/user/UserMedia.vue
- src/WebUI/src/models/restriction.ts
- src/WebUI/src/models/user.ts
- src/WebUI/src/pages/moderator/user/[id].vue
- src/WebUI/src/pages/moderator/user/[id]/information.vue
- src/WebUI/src/services/characters-service.ts
- src/WebUI/src/services/users-service.ts
- src/WebUI/src/symbols/moderator.ts
- src/WebUI/src/types/typed-router.d.ts
- src/WebUI/src/types/vite-components.d.ts
- test/Application.UTest/Users/UpdateUserNoteCommandTest.cs
**Patch notes:** - probably shouldn't post this, but only inform the moderators
- A page with basic information about the user has been added to the section for moderators, where you can write a private note about this user.  @or2e 
<details>
<summary>Screenshots</summary>
</details>
> feat: display user information page

- src/Module.Client/GUI/MapSpriteData.xml
Fixed sprite input for Musa Point and Temple of Posiden
> mod: fix sprite data2

- src/Module.Server/Common/Models/CrpgAgentApplyDamageModel.cs
Cleaned up code,
Ranged 0.8f damage to limbs,
Reduced pierce to head/neck to 1.2f
Note: extend code when viewing to see whole picture
> mod: Body Part Damage

- src/Module.Client/GUI/MapSpriteData.xml
- src/Module.Server/MapRotation/b_maps.txt
- src/Module.Server/ModuleData/Languages/CNs/std_native_strings_xml-zho-CN.xml
- src/Module.Server/ModuleData/Languages/RU/std_native_strings_xml-rus.xml
- src/Module.Server/ModuleData/multiplayer_strings.xml
Made Motte and Bailey by Bullero compatible with conquest.
> feat: add conquest map

- src/Module.Server/ModuleData/dtv/dtv_characters.xml
- src/Module.Server/ModuleData/dtv/dtv_weapons.xml
- src/Module.Server/SubModule.xml
- test/Application.UTest/Application.UTest.csproj
- test/Application.UTest/Common/Files/FileItemsSourceTest.cs
Creates seperate dtv bows in dtv_weapons.xml without manual reload.
`FileItemsSourceTest.cs` checks both items.json & dtv_weapons.xml
> mod: fix dtv archers

- src/Module.Server/ModuleData/dtv/dtv_characters.xml
The +3 weapons come a bit earlier so people can still make use of it and I gave all the lieutenants heirloomed variants too.
Most players use their own +3 anyway so this gives people something to loot and think about, especially newer players.
> Added heirlooms to lieutenants and changed some existing ones.

- src/Module.Client/GUI/MapSpriteData.xml
- src/Module.Server/MapRotation/b_maps.txt
- src/Module.Server/ModuleData/Languages/CNs/std_native_strings_xml-zho-CN.xml
- src/Module.Server/ModuleData/Languages/RU/std_native_strings_xml-rus.xml
- src/Module.Server/ModuleData/multiplayer_strings.xml
Previous PR I forgot a line for motte and bailey. Added that. Also added 2 conquest maps.
Fjallborn - rfl
The White City - Asda
> Add conquest maps + fix

- src/Module.Server/Api/Models/Restrictions/CrpgRestrictionRequest.cs
- src/Module.Server/Common/ChatCommands/Admin/BanCommand.cs
- src/Module.Server/Common/ChatCommands/Admin/MuteCommand.cs
Fixes ban and mute chat commands (reason updates both public and internal record)
> mod: fix admin chat commands

- src/Module.Server/CrpgSubModule.cs
Loads maps into the map pool from a random starting index. Maintains the existing rotation, just impacts the start.
closes #42
> mod: random first map

- src/Module.Server/ModuleData/dtv/dtv_characters.xml
- src/Module.Server/ModuleData/monsters.xml
- src/Module.Server/ModuleData/skins.xml
adds dwarf_bot monster and appropriate skin for dwarf-like proportions!
reduced movespeed of regular dwarf units so they don't look ridiculous
> mod: add custom dwarf skin

- src/Module.Client/GUI/MapSpriteData.xml
- src/Module.Server/MapRotation/b_maps.txt
- src/Module.Server/ModuleData/Languages/CNs/std_native_strings_xml-zho-CN.xml
- src/Module.Server/ModuleData/Languages/RU/std_native_strings_xml-rus.xml
- src/Module.Server/ModuleData/multiplayer_strings.xml
Will be 3 new conquest maps added
> mod: add bebbanburg conquest map

- src/Module.Server/ModuleData/native_parameters.xml
S - 0.65 -> 0.6 (Native 0.5)
A/D - 0.775 -> 0.725 (Native 0.65)
> mod: reduce side and reverse speeds

- src/Module.Server/ModuleData/native_parameters.xml
image showing different value outputs
> mod: enemy capsule size increase

- src/Module.Server/ModuleData/dtv/dtv_characters.xml
- src/Module.Server/ModuleData/dtv/dtv_class_divisions.xml
- src/Module.Server/ModuleData/dtv/dtv_data.xml
Added cavalry units for the Varangian round to make them more of a threat.
> mod: Added cavalry to Varangian round DTV

- src/Module.Server/ModuleData/dtv/dtv_characters.xml
- src/Module.Server/ModuleData/dtv/dtv_data.xml
Made them slower and 2nd wave spawns less
Anybody with more experience might check the stats
> mod: Grey Order adjustment

- src/Module.Server/ModuleData/cloth_bodies.xml
This file is required for custom cloth collision like some of Adamnsexyname's helmets use. Would need this on the itembalancing repo as well to modifie.
Can empty the file if we just want to add the content on the item repo.
> New file clothbodies.xml for custom cloth collisions.

- src/Module.Server/Common/Models/CrpgItemRequirementModel.cs
Update Exporter with xbow STR req increases
Updates the Crafting Exporter with the STR Req increases made by myself under https://github.com/namidaka/crpg/pull/339
as per request:
https://github.com/namidaka/crpg/pull/339#issuecomment-2041135888
> mod: exporter STR reqs update for xbow

- data/constants.json
Reduce reforge cost temporarily
Reduces the reforge cost by 50% temporarily as a gift for the new patch.
> mod : reduce reforge cost temporarily

- src/Module.Server/ModuleData/characters.xml
- src/Module.Server/ModuleData/crafting_pieces.xml
- src/Module.Server/ModuleData/dtv/dtv_characters.xml
- src/Module.Server/ModuleData/items/leg_armors.xml
- src/Module.Server/ModuleData/items/weapons.xml
- adds itembalance changes to refund xbows, bolts
- fixes items.json (str req on xbows & un-exported items)
- makes lederhosen legs visible
> mod: itembalance update

- src/Application/System/Commands/SeedDataCommand.cs
- src/Module.Server/Common/CrpgExperienceTable.cs
Fixes an error where the client would crash if trying to load a maximum level character
> fix: client crash for max level character

- src/Application/Characters/Queries/GetLeaderboardQuery.cs
> webapi: fix leaderboard

- src/Application/Games/Commands/GetGameUserCommand.cs
- test/Application.UTest/Games/GetGameUserCommandTest.cs
updates starting character stats following #372 change
> webapi: update-starting-stats

- src/Persistence/Configurations/UserItemConfiguration.cs
- src/Persistence/Migrations/20241201174640_DisableUniqueUserItem.Designer.cs
- src/Persistence/Migrations/20241201174640_DisableUniqueUserItem.cs
- src/WebUI/locales/en.yml
- src/WebUI/locales/ru.yml
- src/WebUI/src/components/shop/ShopGridItemBuyBtn.vue
- src/WebUI/src/pages/shop.vue
[this task](https://github.com/crpg2/crpg/pull/239) was unfinished. 
This PR removes uniqueness for UserItem index
Merge only after merging https://github.com/crpg2/crpg/pull/410
closed https://github.com/crpg2/crpg/issues/350
> fix: makes userItem not unique

- src/Application/Games/Commands/UpdateGameUsersCommand.cs
- test/Application.UTest/Games/UpdateGameUsersCommandTest.cs
The cost of maintaining items is now taken into account, and empty entries are not logged (e.g. during warm-ups)
> fix: Earning collect stats

- deploy/group_vars/centralservers.yml
> infra: change launcher health check

- src/Module.Server/Common/TeamSelect/CrpgTeamSelectServerComponent.cs
Should fix agents dying when they are reassigned to a different team. Please test this aswell
> Fadeout agents on round end to prevent them from dying.

- src/WebUI/src/components/character/inventory/CharacterInventoryItemUpgrades.vue
- src/WebUI/src/services/item-service.ts
https://discord.com/channels/279063743839862805/1088203928497303715/1315708861419749416
> webui: avoid omit empty values in upgrades table

- src/Module.Server/Common/Models/CrpgItemRequirementModel.cs
seperate str requirements for crossbow depending on light or heavy type
> mod: adjust crossbow str requirement

- src/Module.Client/GUI/MapSpriteData.xml
- src/Module.Server/MapRotation/e_maps.txt
- src/Module.Server/ModuleData/Languages/CNs/std_native_strings_xml-zho-CN.xml
- src/Module.Server/ModuleData/Languages/RU/std_native_strings_xml-rus.xml
- src/Module.Server/ModuleData/multiplayer_strings.xml
> Adds DTV map Simira Fort

- src/Module.Server/ModuleData/dtv/dtv_characters.xml
- src/Module.Server/ModuleData/dtv/dtv_class_divisions.xml
- src/Module.Server/ModuleData/dtv/dtv_data.xml
Added samurai armor to the asian round. 
Changed spawn rates of earlier rounds, making it slightly harder overall with Fancy Lads, Pirates and Vikings jumping out.
Added unit; Berserkir, to viking round.
> Changed equipment, spawns and a new unit for vikings

- src/Module.Server/Modes/TeamDeathmatch/CrpgTeamDeathmatchGameMode.cs
- src/Module.Server/Modes/TeamDeathmatch/CrpgTeamDeathmatchServer.cs
- src/Module.Server/Rewards/CrpgRewardServer.cs
TDM now rewards valour to the top 20% of players from each team
Multi reduces each minute unless valour is achieved
Reduced afk timer to 30 seconds in tdm
Minimum of 3 players required for valour to start being awarded
MMR is now tracked for TDM (but hidden from players) to improve scoring and therefore valour
> mod: rework tdm rewards

- src/Module.Server/ModuleData/dtv/dtv_characters.xml
Gave the viscount a metal heater shield and 1 shield skill.
> mod: add viscount shield

- src/Module.Server/Common/TeamSelect/CrpgTeamSelectServerComponent.cs
> fix: only fadeout agents who are teamswapped

- src/Module.Server/Modes/TeamDeathmatch/CrpgTeamDeathmatchServer.cs
- src/Module.Server/Rewards/CrpgRewardServer.cs
Improves rewards for players by increasing multi by 1x per reward tick for winning team. Valour awarded for top 20% of losing players.
> mod: add TDM winning side multi and only give valour to losing side

- src/Application/System/Commands/SeedDataCommand.cs
Add Yeldur to SeedData for testing WebUI changes
> Add SeedData

- src/Module.Server/Common/Models/CrpgItemValueModel.cs
Adjusted budget for all 1h and 2h axes for after they get cleave
ItemBalance change: https://github.com/namidaka/itembalancing/pull/567
> Budget adjustment for 1h & 2h axes for after cleave addition

- src/WebUI/locales/en.yml
- src/WebUI/src/composables/shop/use-filters.ts
- src/WebUI/src/models/item.ts
- src/WebUI/src/services/item-search-service/aggregations.ts
- src/WebUI/src/services/item-search-service/indexator.ts
- src/WebUI/src/services/item-service.ts
> webui: group range weapons

- src/Module.Server/Common/CrpgScoreboardComponent.cs
Increased score gain for mount damage slightly to incentivise cavalry hunting
> Increased score for mount damage

- src/WebUI/locales/en.yml
- src/WebUI/src/components/app/MainNavigation.vue
- src/WebUI/src/pages/credits/index.vue
Add Credits page to site
This change adds an official credits page to the website that includes all known people who have contributed to the mod, be that through moderation, development, or otherwise.
> webUI: Add Credits page to site

- src/Module.Server/Common/Models/CrpgAgentApplyDamageModel.cs
- src/Module.Server/Common/Models/CrpgAgentStatCalculateModel.cs
- Improves windup speed and accuracy for throwing
- Increase DTV throwing damage by 30%
> Throwing fix attempt

- src/Directory.Build.props
- src/Module.Editor/SubModule.xml
- src/Module.Server/SubModule.xml
mod: bump version to v1.12.120
> mod: bump version to v1.12.120

- src/Directory.Build.props
- src/Module.Editor/SubModule.xml
- src/Module.Server/SubModule.xml
mod: bump version to v1.12.121
> mod: bump version to v1.12.121

- src/Module.Client/DataExport/ItemExporter.cs
- src/Module.Server/Common/Models/CrpgItemRequirementModel.cs
- src/Module.Server/Common/Models/CrpgItemValueModel.cs
Light gun usage set value and req update to allow - https://github.com/crpg2/itembalancing/pull/654
> light gun usage set for value and req

- src/Module.Server/ModuleData/native_parameters.xml
Capsule increase step 2: https://github.com/crpg2/crpg/pull/567
> Capsule increase step 2

- src/Directory.Build.props
- src/Module.Editor/SubModule.xml
- src/Module.Server/SubModule.xml
mod: bump version to v1.12.122
> mod: bump version to v1.12.122
